# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            De datorum scientia
tagline:          and everything else
url:              http://ngrislain.github.io/
paginate:         1
baseurl:          /
author:
  name:           Nicolas Grislain
  url:            https://twitter.com/ngrislain
  email:          nicolas.grislain@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ngrislain/ngrislain.github.io

theme: jekyll-theme-cayman