# Site settings
title: De datorum scientia
tagline: thoughts about data-science
#email: nicolas.grislain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog to write down thoughts about data-science
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ngrislain
github_username:  ngrislain

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty
relative_permalinks: true