import VersoBlog

open Verso
open Genre Blog
open Output Html
open Template
open Verso.Genre.Blog Theme

namespace Site

open Verso.Genre.Blog

private def siteTitle : String := "NGrislain"

private def monthName : Nat → String
  | 1 => "January"
  | 2 => "February"
  | 3 => "March"
  | 4 => "April"
  | 5 => "May"
  | 6 => "June"
  | 7 => "July"
  | 8 => "August"
  | 9 => "September"
  | 10 => "October"
  | 11 => "November"
  | 12 => "December"
  | n => toString n

private def formatDate (date : Verso.Genre.Blog.Date) : String :=
  s!"{monthName date.month} {date.day}, {date.year}"

private def renderCategoryLinks (catAddr : String → String) (cats : List Post.Category) : Html :=
  if cats.isEmpty then
    Html.empty
  else
    {{
      <div class="article-list-tags">
        {{ cats.toArray.map (fun cat => {{<a href={{catAddr cat.slug}}>{{cat.name}}</a>}}) }}
      </div>
    }}

private def renderMetadataFooter (catAddr : String → String) (date : Verso.Genre.Blog.Date) (cats : List Post.Category) : Html :=
  let catLinks := renderCategoryLinks catAddr cats
  {{
    <div class="article-list-footer">
      <span class="article-list-date">{{formatDate date}}</span>
      {{ if cats.isEmpty then Html.empty else {{<span class="article-list-divider">"-"</span>}} }}
      {{ if cats.isEmpty then Html.empty else catLinks }}
    </div>
  }}

private def navigation : Template := do
  pure {{
    <nav class="header-nav">
      <a href="." class="header-logo">{{siteTitle}}</a>
      <ul class="header-links">
        {{ ← Theme.dirLinks (← read).site }}
      </ul>
    </nav>
  }}

private def footer : Html :=
  {{
    <footer class="footer">
      <p>
        "This site is generated by Verso."
      </p>
    </footer>
  }}

private def primary : Template := do
  let postsHtml :=
    match (← param? (α := Html) "posts") with
    | none => Html.empty
    | some html => {{<ul class="article-list">{{html}}</ul>}}
  let categoryDirectory :=
    match (← param? (α := Post.Categories) "categories") with
    | none => Html.empty
    | some ⟨cats⟩ => {{
        <div class="tags-page">
          <ul class="header-tags">
            {{ cats.map fun (target, cat) => {{<li><a href={{target}}>{{cat.name}}</a></li>}} }}
          </ul>
        </div>
      }}
  return {{
    <html>
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta http-equiv="x-ua-compatible" content="ie=edge"/>
        <title>{{← param (α := String) "title"}}" | "{{siteTitle}}</title>
        {{← builtinHeader}}
        <link rel="stylesheet" href="static/chalk.css" type="text/css"/>
      </head>
      <body>
        <main>
          <div class="grid grid-centered">
            <div class="grid-cell">
              {{← navigation}}
              {{← param "content"}}
              {{postsHtml}}
              {{categoryDirectory}}
              {{footer}}
            </div>
          </div>
        </main>
      </body>
    </html>
  }}

private def page : Template := do
  pure {{
    <article class="article">
      <header class="article-header">
        <h1>{{← param "title"}}</h1>
      </header>
      <div class="article-content">
        {{← param "content"}}
      </div>
    </article>
  }}

private def post : Template := do
  let catAddr ← do
    if let some p := (← param? (α := String) "path") then
      pure fun slug => p ++ "/" ++ slug
    else
      pure fun slug => slug
  let metadataHtml :=
    match (← param? (α := Post.PartMetadata) "metadata") with
    | none => Html.empty
    | some md => renderMetadataFooter catAddr md.date md.categories
  pure {{
    <article class="article">
      <header class="article-header">
        <h1>{{← param "title"}}</h1>
        {{metadataHtml}}
      </header>
      <div class="article-content">
        {{← param "content"}}
      </div>
    </article>
  }}

private def category : Template := do
  let category : Post.Category ← param "category"
  pure {{
    <section class="tags-page">
      <h1 class="tags-page-header">{{category.name}}</h1>
    </section>
  }}

private def archiveEntry : Template := do
  let post : BlogPost ← param "post"
  let summary ← param "summary"
  let target ←
    if let some p := (← param? (α := String) "path") then
      pure <| p ++ "/" ++ (← post.postName')
    else
      post.postName'
  let catAddr ←
    if let some p := (← param? (α := String) "path") then
      pure fun slug => p ++ "/" ++ slug
    else
      pure fun slug => slug
  let metadataHtml :=
    match post.contents.metadata with
    | none => Html.empty
    | some md => renderMetadataFooter catAddr md.date md.categories
  pure #[{{
    <li class="article-list-item">
      <a href={{target}}>
        <h5>{{post.contents.titleString}}</h5>
      </a>
      {{metadataHtml}}
      {{summary}}
      <a href={{target}} class="read-more">"Read more"</a>
    </li>
  }}]

/-- Chalk-inspired theme matching https://chalk.nielsenramon.com/posts/introducing-chalk. -/
def chalkTheme : Theme :=
  { Theme.default with
    primaryTemplate := primary
    pageTemplate := page
    postTemplate := post
    categoryTemplate := category
    archiveEntryTemplate := archiveEntry }

end Site
