import VersoBlog

open Verso
open Genre Blog
open Output Html
open Template
open Verso.Genre.Blog Theme

namespace Site

open Verso.Genre.Blog

private def siteTitle : String := "NGrislain"

private def monthName : Nat → String
  | 1 => "January"
  | 2 => "February"
  | 3 => "March"
  | 4 => "April"
  | 5 => "May"
  | 6 => "June"
  | 7 => "July"
  | 8 => "August"
  | 9 => "September"
  | 10 => "October"
  | 11 => "November"
  | 12 => "December"
  | n => toString n

private def formatDate (date : Verso.Genre.Blog.Date) : String :=
  s!"{monthName date.month} {date.day}, {date.year}"

private def renderCategoryLinks (catAddr : String → String) (cats : List Post.Category) : Html :=
  if cats.isEmpty then
    Html.empty
  else
    {{
      <span class="post-tags-inline">
        {{ cats.toArray.map (fun cat => {{<a href={{catAddr cat.slug}}>{{cat.name}}</a>}}) }}
      </span>
    }}

private def renderMetadataFooter (catAddr : String → String) (date : Verso.Genre.Blog.Date) (cats : List Post.Category) : Html :=
  let catLinks := renderCategoryLinks catAddr cats
  {{
    <div class="post-meta">
      <span>{{formatDate date}}</span>
      {{ if cats.isEmpty then Html.empty else {{<span>" · "</span>}} }}
      {{ if cats.isEmpty then Html.empty else catLinks }}
    </div>
  }}

private def themeToggleScript : String :=
  "
  (function() {
    var theme = localStorage.getItem('pref-theme');
    if (theme === 'dark') {
      document.documentElement.setAttribute('data-theme', 'dark');
    } else if (theme === 'light') {
      document.documentElement.setAttribute('data-theme', 'light');
    } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      document.documentElement.setAttribute('data-theme', 'dark');
    }
  })();
  "

private def highlightInitScript : String :=
  "
  document.querySelectorAll('pre').forEach(function(pre) {
    if (!pre.querySelector('.hl') && !pre.classList.contains('hl')) {
      pre.classList.add('language-lean');
      hljs.highlightElement(pre);
    }
  });
  "

private def themeToggleClickScript : String :=
  "
  document.getElementById('theme-toggle').addEventListener('click', function() {
    var current = document.documentElement.getAttribute('data-theme');
    var next = (current === 'dark') ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    localStorage.setItem('pref-theme', next);
  });
  "

private def navigation : Template := do
  pure {{
    <header class="header">
      <nav class="nav">
        <div class="logo">
          <a href="." class="site-title">{{siteTitle}}</a>
        </div>
        <ul class="nav-links">
          {{ ← Theme.dirLinks (← read).site }}
          <li class="logo-switches">
            <button id="theme-toggle" title="Toggle dark mode">"☀️"</button>
          </li>
        </ul>
      </nav>
    </header>
  }}

private def footer : Html :=
  {{
    <footer class="footer">
      <span>"This site is generated by "</span>
      <a href="https://github.com/leanprover/verso">"Verso"</a>
      <span>"."</span>
    </footer>
  }}

private def primary : Template := do
  let postsHtml :=
    match (← param? (α := Html) "posts") with
    | none => Html.empty
    | some html => html
  let categoryDirectory :=
    match (← param? (α := Post.Categories) "categories") with
    | none => Html.empty
    | some ⟨cats⟩ => {{
        <div class="tags-page">
          <ul class="tags-list">
            {{ cats.map fun (target, cat) => {{<li><a href={{target}}>{{cat.name}}</a></li>}} }}
          </ul>
        </div>
      }}
  return {{
    <html>
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta http-equiv="x-ua-compatible" content="ie=edge"/>
        <title>{{← param (α := String) "title"}}" | "{{siteTitle}}</title>
        <script>{{themeToggleScript}}</script>
        {{← builtinHeader}}
        <link rel="icon" type="image/svg+xml" href="static/favicon.svg"/>
        <link rel="stylesheet" href="static/chalk.css" type="text/css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
        <script src="https://unpkg.com/highlightjs-lean@1.2.0/dist/lean.min.js"></script>
      </head>
      <body>
        {{← navigation}}
        <main class="main">
          {{← param "content"}}
          {{postsHtml}}
          {{categoryDirectory}}
        </main>
        {{footer}}
        <script>{{themeToggleClickScript}}</script>
        <script>{{highlightInitScript}}</script>
      </body>
    </html>
  }}

private def page : Template := do
  pure {{
    <article>
      <header class="post-header">
        <h1 class="post-title">{{← param "title"}}</h1>
      </header>
      <div class="post-content">
        {{← param "content"}}
      </div>
    </article>
  }}

private def post : Template := do
  let catAddr ← do
    if let some p := (← param? (α := String) "path") then
      pure fun slug => p ++ "/" ++ slug
    else
      pure fun slug => slug
  let metadataHtml :=
    match (← param? (α := Post.PartMetadata) "metadata") with
    | none => Html.empty
    | some md => renderMetadataFooter catAddr md.date md.categories
  pure {{
    <article>
      <header class="post-header">
        <h1 class="post-title">{{← param "title"}}</h1>
        {{metadataHtml}}
      </header>
      <div class="post-content">
        {{← param "content"}}
      </div>
    </article>
  }}

private def category : Template := do
  let category : Post.Category ← param "category"
  pure {{
    <div class="tags-page">
      <h1>{{category.name}}</h1>
    </div>
  }}

private def archiveEntry : Template := do
  let post : BlogPost ← param "post"
  let summary ← param "summary"
  let target ←
    if let some p := (← param? (α := String) "path") then
      pure <| p ++ "/" ++ (← post.postName')
    else
      post.postName'
  let catAddr ←
    if let some p := (← param? (α := String) "path") then
      pure fun slug => p ++ "/" ++ slug
    else
      pure fun slug => slug
  let metadataHtml :=
    match post.contents.metadata with
    | none => Html.empty
    | some md => renderMetadataFooter catAddr md.date md.categories
  pure #[{{
    <div class="post-entry">
      <header class="entry-header">
        <h2><a href={{target}}>{{post.contents.titleString}}</a></h2>
      </header>
      {{metadataHtml}}
      <div class="entry-content">
        {{summary}}
      </div>
      <a class="entry-link" href={{target}} aria-label={{post.contents.titleString}}></a>
    </div>
  }}]

/-- PaperMod-inspired theme. -/
def chalkTheme : Theme :=
  { Theme.default with
    primaryTemplate := primary
    pageTemplate := page
    postTemplate := post
    categoryTemplate := category
    archiveEntryTemplate := archiveEntry }

end Site
